# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import konkurs.models
import konkurs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('year', models.IntegerField(default=2018, primary_key=True, serialize=False)),
                ('beginDate', models.DateField(default=datetime.date(2018, 10, 1))),
                ('endDate', models.DateField(default=datetime.date(2018, 5, 20))),
                ('reasultDate', models.DateField(default=datetime.date(2018, 10, 31))),
                ('plakat', models.FileField(upload_to=konkurs.models.directory_path)),
                ('regulamin', models.FileField(upload_to=konkurs.models.directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('work', models.FileField(upload_to=konkurs.models.directory_path, validators=[konkurs.validators.only_pdf])),
                ('survey', models.FileField(upload_to=konkurs.models.directory_path, validators=[konkurs.validators.only_pdf])),
                ('certification', models.FileField(upload_to=konkurs.models.directory_path, validators=[konkurs.validators.only_pdf])),
                ('attachements', models.FileField(upload_to=konkurs.models.directory_path)),
                ('accepted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.Author')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.Competition')),
            ],
        ),
    ]
