# Generated by Django 3.2.6 on 2021-08-10 18:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cellphone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Phone number ex: '+41524204242'", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Phone number ex: '+41524204242'", max_length=128, region=None),
        ),
    ]
