# Generated by Django 3.2.6 on 2021-08-10 18:23

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210810_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=users.models.CountryField(verbose_name='Nationality'),
        ),
    ]
