# Generated by Django 2.0 on 2018-01-10 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myrating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='work',
        ),
        migrations.RemoveField(
            model_name='work',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 22, 32, 56, 25072)),
        ),
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
