# Generated by Django 2.0 on 2017-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performence',
            name='time',
            field=models.DurationField(),
        ),
    ]
