# Generated by Django 2.0 on 2017-12-17 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='uczestnik',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DigitalGraphic',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('obraz', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='LandArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('technika', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Performence',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('time', models.CharField(max_length=20)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('technika', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('wymiary', models.CharField(max_length=30)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='UrbanArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('time', models.CharField(max_length=20)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='VirtualArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.AddField(
            model_name='work',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.Uczestnik'),
        ),
        migrations.AddField(
            model_name='work',
            name='reviews',
            field=models.ManyToManyField(through='konkurs.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='konkurs.Work'),
        ),
    ]
