# Generated by Django 2.0 on 2017-12-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
    ]
