# Generated by Django 2.0 on 2018-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='alias',
            field=models.CharField(max_length=50, null=True, verbose_name='Alias'),
        ),
    ]
