# Generated by Django 2.0 on 2017-12-17 16:02

import datetime
from django.db import migrations, models
import konkurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='birthday',
            field=models.DateField(default=datetime.date.today, validators=[konkurs.models.MinAgeValidator(18)]),
        ),
    ]
