# Generated by Django 2.0 on 2017-12-27 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 3, 48, 663711)),
        ),
    ]
