# Generated by Django 2.0 on 2017-12-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0002_auto_20171205_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczestnik',
            name='place_of_birth',
            field=models.CharField(default='Kalisz', max_length=30, verbose_name='Place Of Birth'),
        ),
    ]
