# Generated by Django 2.0 on 2017-12-27 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0002_work_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 34, 46, 710071)),
        ),
    ]
