# Generated by Django 2.0 on 2017-12-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0003_uczestnik_place_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uczestnik',
            old_name='street_line1',
            new_name='street_line',
        ),
    ]
