# Generated by Django 2.0 on 2018-01-10 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0003_auto_20180110_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 22, 56, 34, 229712)),
        ),
    ]
