# Generated by Django 2.0 on 2018-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0003_auto_20180115_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='uczestnik',
            name='street_line',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='uczestnik',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='ZIP code'),
        ),
    ]
