# Generated by Django 2.0 on 2017-12-25 16:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0004_auto_20171225_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performence',
            name='time',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 1200), message='Za długi film')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 1200), message='Za długi film')]),
        ),
    ]
