# Generated by Django 2.0 on 2017-12-29 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0004_auto_20171229_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 19, 36, 1, 873132)),
        ),
    ]
