# Generated by Django 2.0 on 2017-12-23 15:21

from django.db import migrations, models
import konkurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0004_auto_20171222_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalgraphic',
            name='obraz',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='landart',
            name='obraz1',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='landart',
            name='obraz2',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='landart',
            name='obraz3',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='paint',
            name='obraz',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='performence',
            name='obraz',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='obraz1',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='obraz2',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='obraz3',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='urbanart',
            name='obraz1',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='urbanart',
            name='obraz2',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='urbanart',
            name='obraz3',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='obraz',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='virtualart',
            name='obraz1',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='virtualart',
            name='obraz2',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
        migrations.AlterField(
            model_name='virtualart',
            name='obraz3',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
    ]
