# Generated by Django 2.0 on 2017-12-05 18:38

from django.db import migrations, models
import konkurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0004_auto_20171205_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='birthday',
            field=models.DateField(validators=[konkurs.models.MinAgeValidator(18)]),
        ),
    ]
