# Generated by Django 2.0 on 2018-01-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0005_auto_20180120_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='stratDate',
            new_name='startDate',
        ),
    ]
