# Generated by Django 2.0 on 2017-12-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0005_auto_20171205_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sculpture', 'Rzeźba'), ('Paint', 'Obraz'), ('Virtual Art', 'Sztuka Wirtualna'), ('Digital Graphics', 'Grafika cyfrowa'), ('Photograph', 'Zdjęcie'), ('Video art', 'Video'), ('Performence', 'Występ'), ('LandArt', 'LandArt'), ('UrbanArt', 'UrbanArt')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('video_url', models.URLField()),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.AddField(
            model_name='work',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.Uczestnik'),
        ),
    ]
