# Generated by Django 2.0 on 2017-12-23 15:21

from django.db import migrations, models
import konkurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0005_auto_20171223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='obraz',
            field=models.ImageField(upload_to=konkurs.models.directory_path),
        ),
    ]
