# Generated by Django 2.0 on 2018-01-11 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0006_auto_20180111_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 12, 32, 44, 599390)),
        ),
    ]
