# Generated by Django 2.0 on 2017-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0006_auto_20171223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='obraz',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
