# Generated by Django 2.0 on 2018-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0006_auto_20180120_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='oplacona',
            field=models.BooleanField(default=False),
        ),
    ]
