# Generated by Django 2.0 on 2017-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0006_auto_20171205_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='video_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
