# Generated by Django 2.2.3 on 2019-07-23 17:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0007_work_oplacona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uczestnik',
            name='cellphone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
