# Generated by Django 2.0 on 2017-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0007_sculpture_video_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
    ]
