# Generated by Django 2.0 on 2018-01-12 17:03

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0007_auto_20180111_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 18, 3, 59, 291877)),
        ),
    ]
