# Generated by Django 2.0 on 2018-01-12 19:41

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0008_auto_20180112_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('kwota', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 20, 41, 30, 482160)),
        ),
        migrations.AddField(
            model_name='work',
            name='awards',
            field=models.ManyToManyField(to='konkurs.Award'),
        ),
    ]
