# Generated by Django 2.0 on 2017-12-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0008_remove_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('technika', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='wymiary',
            field=models.CharField(max_length=30),
        ),
    ]
