# Generated by Django 2.0 on 2017-12-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0009_auto_20171205_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalGraphic',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('obraz', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='LandArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Performence',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=20)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('technika', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='UrbanArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=20)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
            ],
            bases=('konkurs.work',),
        ),
        migrations.CreateModel(
            name='VirtualArt',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='konkurs.Work')),
                ('title', models.CharField(max_length=30)),
                ('wymiary', models.CharField(max_length=10)),
                ('opis', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('obraz1', models.ImageField(upload_to='')),
                ('obraz2', models.ImageField(upload_to='')),
                ('obraz3', models.ImageField(upload_to='')),
                ('video_url', models.URLField()),
                ('video_password', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            bases=('konkurs.work',),
        ),
    ]
