# Generated by Django 2.0 on 2017-12-05 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konkurs', '0010_digitalgraphic_landart_performence_picture_urbanart_video_virtualart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Autor', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='konkurs.Work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='reviews',
            field=models.ManyToManyField(through='konkurs.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
