# Generated by Django 2.0 on 2017-12-29 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0012_auto_20171229_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 19, 49, 16, 974509)),
        ),
    ]
